<a href="https://colab.research.google.com/github/PriFranca/Estudo-Ds/blob/master/Estatistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Conhecendo melhor nossa base de consumidores: qual estado possui os clientes com melhores pontuações de crédito?**

#Objetivo

Queremos conhecer melhor nossos clientes por estado. Para isso, iniciamos uma análise na pontuação de crédito. Para realizar a verificação inicial, precisamos de alguns valores. Os valores são a média, a mediana, a moda e o desvio padrão da pontuação de crédito.

#Tópicos
Neste desafio você aprenderá:

*   Média;
*   Mediana;
*   Moda;
*   Desvio padrão.

#Detalhes
Detalhes
A resposta deve conter os valores da média, mediana, moda e desvio padrão da pontuação de crédito para cada estado do dataset. O arquivo para submissão deve estar em formato json, conforme o arquivo exemplo “submission.json”.

OBSERVAÇÃO: É recomendado utilizar Python e pandas para esse desafio, mas também é possível utilizar outras ferramentas e linguagens de programação.

Descrição dos dados: ‘id’: Identificador do cliente ‘sobrenome’: Sobrenome do cliente ‘pontuacao_credito’: Pontuação de crédito do cliente (quanto maior, melhor o cliente geralmente) ‘estado_residencia’: Estado de residência do cliente ‘genero’: Gênero do cliente ‘nivel_estabilidade’: Nível de estabilidade do cliente ‘saldo_conta’: Saldo disponível na conta do cliente ‘numero_produtos’: Número de produtos que o cliente consome ‘possui_cartao_de_credito’: Possui um cartão de crédito cadastrado ‘membro_ativo’: Membro acessa e consome frequentemente

Obs: Os dados são fictícios, mas tentam representar a realidade de uma base de clientes de um produto SaaS.

In [ ]:
import pandas as pd
import numpy as np
import json

In [ ]:
df = pd.read_csv('desafio1.csv')

In [ ]:
df.head()

   RowNumber  ... membro_ativo
0          1  ...            1
1          2  ...            1
2          3  ...            0
3          4  ...            0
4          5  ...            1

[5 rows x 12 columns]

In [ ]:
df.shape

(7000, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   RowNumber                 7000 non-null   int64
 1   id                        7000 non-null   object
 2   sobrenome                 7000 non-null   object
 3   pontuacao_credito         7000 non-null   int64
 4   estado_residencia         7000 non-null   object
 5   genero                    7000 non-null   object
 6   idade                     7000 non-null   int64
 7   nivel_estabilidade        7000 non-null   int64
 8   saldo_conta               7000 non-null   float64
 9   numero_produtos           7000 non-null   int64
 10  possui_cartao_de_credito  7000 non-null   int64
 11  membro_ativo              7000 non-null   int64
dtypes: float64(1), int64(7), object(4)
memory usage: 656.4+ KB

In [ ]:
df.describe().T

                           count          mean  ...         75%        max
RowNumber                 7000.0   3500.500000  ...    5250.250    7000.00
pontuacao_credito         7000.0    649.787000  ...     717.000     850.00
idade                     7000.0     38.892714  ...      44.000      92.00
nivel_estabilidade        7000.0      5.010286  ...       7.250      10.00
saldo_conta               7000.0  76471.883751  ...  127537.155  250898.09
numero_produtos           7000.0      1.526000  ...       2.000       4.00
possui_cartao_de_credito  7000.0      0.703286  ...       1.000       1.00
membro_ativo              7000.0      0.512143  ...       1.000       1.00

[8 rows x 8 columns]

In [ ]:
def resposta(dataframe):
    estados = dataframe['estado_residencia'].unique()
    submissao = pd.read_json('submission.json', dtype='float')
    for i in estados:
        estado = dataframe[(dataframe['estado_residencia'] == i) ]['pontuacao_credito']
        submissao[i]['moda'] = estado.mode()
        submissao[i]['mediana'] = estado.median()
        submissao[i]['media'] = estado.mean()
        submissao[i]['desvio_padrao'] = estado.std()
    submissao.to_json('submission.json', double_precision=15)
    return submissao

In [ ]:
resposta(df)

                       SC          RS          PR
moda           850.000000  850.000000  850.000000
mediana        653.000000  650.000000  650.000000
media          649.537653  651.105143  648.961294
desvio_padrao   97.233493   95.136598   98.607186